name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install ".[docs]"
          # if there is doc or tutorial requirements.txt file then install it
          if [ -f ./docs/tutorials/requirements.txt ]; then
            pip install -r ./docs/tutorials/requirements.txt
          fi
          if [ -f ./docs/requirements.txt ]; then
            pip install -r ./docs/requirements.txt
          fi

      - name: Build and Commit
        uses: sphinx-notes/pages@2.1
        with:
          documentation_path: docs

      - name: Push changes
        if: ${{ github.event_name == 'push' }}
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.SPHINX_DOCUMENTATION }}
          branch: gh-pages
